[project]
authors = ["retrofuel"]
entry = "main.sw"
license = "Apache-2.0"
name = "koby_staking_contract"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", tag = "v0.66.5" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.2" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.1" }